name: Documentation build & push

on:
  push:
    branches:
      - master
    paths:
      - libraries/**

  pull_requests:
    branches:
      - master
    paths:
      - libraries/**


jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test

  push:
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name != 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} && npm run docs
      - name: Git configuration
        run: |
          git config --global user.name "Github CI"
          git config --global user.email "<>"
      - name: Add libraries.rst to the staging area
        run: git add -f docs/libraries.rst
      - name: Commit the libraries if there are changes
        run: >
          git diff-index --quiet head || git commit -m "Documentation update: $(date +'%d %b %Y')"
      - name: Push changes into the repository
        run: git push origin


